import React, { useEffect, useState } from "react";
import { useAuth } from "@/contexts/AuthContext";
import { supabase } from "@/integrations/supabase/client";
import { FileText, Download, Github, Mail, MapPin, Code2, Loader2 } from "lucide-react";
import jsPDF from "jspdf";
import { toast } from "sonner";

const ResumeBuilderPage: React.FC = () => {
  const { user, userCode } = useAuth();
  const [profile, setProfile] = useState<any>(null);
  const [xp, setXp] = useState(0);
  const [badgeCount, setBadgeCount] = useState(0);
  const [projects, setProjects] = useState<any[]>([]);
  const [dsa, setDsa] = useState({ solved: 0, score: 0 });
  const [generating, setGenerating] = useState(false);

  useEffect(() => {
    if (!user) return;
    Promise.all([
      supabase.from("profiles").select("*").eq("user_id", user.id).single(),
      supabase.from("xp_logs").select("amount").eq("user_id", user.id),
      supabase.from("user_badges").select("id", { count: "exact", head: true }).eq("user_id", user.id),
      supabase.from("projects").select("*").eq("user_id", user.id),
      supabase.from("dsa_submissions").select("score, status").eq("user_id", user.id),
    ]).then(([p, x, b, proj, dsaRes]) => {
      setProfile(p.data);
      setXp(((x as any).data || []).reduce((s: number, r: any) => s + r.amount, 0));
      setBadgeCount((b as any).count || 0);
      setProjects((proj as any).data || []);
      const accepted = ((dsaRes as any).data || []).filter((d: any) => d.status === "accepted");
      setDsa({ solved: accepted.length, score: accepted.reduce((s: number, d: any) => s + d.score, 0) });
    });
  }, [user]);

  const generatePDF = () => {
    if (!profile) return;
    setGenerating(true);
    const doc = new jsPDF();
    const w = doc.internal.pageSize.getWidth();

    // Header
    doc.setFillColor(10, 15, 10);
    doc.rect(0, 0, w, 45, "F");
    doc.setTextColor(0, 204, 51);
    doc.setFontSize(24);
    doc.setFont("courier", "bold");
    doc.text(profile.display_name || profile.user_code, 20, 25);
    doc.setFontSize(10);
    doc.setTextColor(100, 150, 100);
    doc.text(`${profile.user_code}@codeclub.pro | ${(profile as any).branch || "CS"} | GitHub: ${(profile as any).github_username || "N/A"}`, 20, 35);

    let y = 55;
    const section = (title: string) => {
      doc.setDrawColor(0, 204, 51);
      doc.line(20, y, w - 20, y);
      y += 8;
      doc.setTextColor(0, 204, 51);
      doc.setFontSize(14);
      doc.setFont("courier", "bold");
      doc.text(`> ${title}`, 20, y);
      y += 10;
      doc.setTextColor(180, 210, 180);
      doc.setFontSize(10);
      doc.setFont("courier", "normal");
    };

    // Stats
    section("STATS");
    doc.text(`XP: ${xp}  |  Badges: ${badgeCount}  |  Problems Solved: ${dsa.solved}  |  Total Score: ${dsa.score}`, 20, y);
    y += 12;

    // Skills
    if ((profile as any).skills?.length) {
      section("SKILLS");
      doc.text((profile as any).skills.join("  •  "), 20, y);
      y += 12;
    }

    // Bio
    if (profile.bio) {
      section("ABOUT");
      const lines = doc.splitTextToSize(profile.bio, w - 40);
      doc.text(lines, 20, y);
      y += lines.length * 6 + 8;
    }

    // Projects
    if (projects.length) {
      section("PROJECTS");
      projects.forEach(p => {
        doc.setTextColor(0, 204, 51);
        doc.setFont("courier", "bold");
        doc.text(`• ${p.name}`, 20, y);
        y += 6;
        doc.setTextColor(180, 210, 180);
        doc.setFont("courier", "normal");
        if (p.description) {
          const desc = doc.splitTextToSize(p.description, w - 45);
          doc.text(desc, 25, y);
          y += desc.length * 5 + 2;
        }
        if (p.tech_stack?.length) {
          doc.text(`Tech: ${p.tech_stack.join(", ")}`, 25, y);
          y += 6;
        }
        y += 4;
      });
    }

    // Footer
    doc.setTextColor(80, 100, 80);
    doc.setFontSize(8);
    doc.text("Generated by CodeClub Pro — Competitive Coding Platform", 20, 285);

    doc.save(`${profile.user_code}_resume.pdf`);
    toast.success("Resume downloaded!");
    setGenerating(false);
  };

  return (
    <div className="max-w-3xl space-y-6 animate-fade-in">
      <div>
        <p className="text-sm text-muted-foreground font-mono mb-1">$ resume --generate</p>
        <h1 className="text-2xl font-bold text-foreground"><span className="text-primary">Resume</span> Builder</h1>
      </div>

      <div className="terminal-card rounded-lg p-6">
        <div className="flex items-center gap-2 mb-4">
          <div className="w-3 h-3 rounded-full bg-neon-green/60" />
          <span className="text-xs text-muted-foreground font-mono">preview.md</span>
        </div>

        {profile ? (
          <div className="space-y-4">
            <div className="flex items-center gap-4">
              <div className="w-12 h-12 rounded-md bg-primary/10 border border-primary/20 flex items-center justify-center">
                <Code2 className="w-6 h-6 text-primary" />
              </div>
              <div>
                <h2 className="text-lg font-bold text-foreground">{profile.display_name || profile.user_code}</h2>
                <p className="text-xs text-muted-foreground font-mono">{(profile as any).branch || "Student"} | {userCode}</p>
              </div>
            </div>

            <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
              <div className="bg-background rounded-md p-3 text-center border border-border">
                <p className="text-lg font-bold text-primary">{xp}</p>
                <p className="text-xs text-muted-foreground">XP</p>
              </div>
              <div className="bg-background rounded-md p-3 text-center border border-border">
                <p className="text-lg font-bold text-foreground">{badgeCount}</p>
                <p className="text-xs text-muted-foreground">Badges</p>
              </div>
              <div className="bg-background rounded-md p-3 text-center border border-border">
                <p className="text-lg font-bold text-foreground">{dsa.solved}</p>
                <p className="text-xs text-muted-foreground">Solved</p>
              </div>
              <div className="bg-background rounded-md p-3 text-center border border-border">
                <p className="text-lg font-bold text-foreground">{projects.length}</p>
                <p className="text-xs text-muted-foreground">Projects</p>
              </div>
            </div>

            {(profile as any).skills?.length > 0 && (
              <div>
                <p className="text-xs text-primary font-mono mb-2">skills[]:</p>
                <div className="flex gap-2 flex-wrap">
                  {(profile as any).skills.map((s: string) => (
                    <span key={s} className="text-xs px-2 py-1 rounded-md bg-primary/10 text-primary border border-primary/20">{s}</span>
                  ))}
                </div>
              </div>
            )}

            {profile.bio && (
              <div>
                <p className="text-xs text-primary font-mono mb-1">bio:</p>
                <p className="text-sm text-foreground">{profile.bio}</p>
              </div>
            )}

            <button onClick={generatePDF} disabled={generating}
              className="flex items-center gap-2 px-6 py-3 rounded-md bg-primary text-primary-foreground font-bold hover:bg-primary/90 transition-all glow-border disabled:opacity-50">
              {generating ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
              $ download --pdf
            </button>
          </div>
        ) : (
          <div className="text-center py-8">
            <Loader2 className="w-8 h-8 text-primary mx-auto animate-spin" />
            <p className="text-muted-foreground mt-2 font-mono">Loading profile data...</p>
          </div>
        )}
      </div>
    </div>
  );
};

export default ResumeBuilderPage;
